//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClientWeb.UserService {
    using System.Runtime.Serialization;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="UserType", Namespace="http://schemas.datacontract.org/2004/07/SchoolService")]
    public enum UserType : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Student = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Teacher = 2,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="UserService.IUserService")]
    public interface IUserService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserService/SearchTeacher", ReplyAction="http://tempuri.org/IUserService/SearchTeacherResponse")]
        System.Data.DataSet SearchTeacher(string input);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserService/SearchTeacher", ReplyAction="http://tempuri.org/IUserService/SearchTeacherResponse")]
        System.Threading.Tasks.Task<System.Data.DataSet> SearchTeacherAsync(string input);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserService/GetTeacher", ReplyAction="http://tempuri.org/IUserService/GetTeacherResponse")]
        System.Data.DataSet GetTeacher(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserService/GetTeacher", ReplyAction="http://tempuri.org/IUserService/GetTeacherResponse")]
        System.Threading.Tasks.Task<System.Data.DataSet> GetTeacherAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserService/GetTeachers", ReplyAction="http://tempuri.org/IUserService/GetTeachersResponse")]
        System.Data.DataSet GetTeachers();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserService/GetTeachers", ReplyAction="http://tempuri.org/IUserService/GetTeachersResponse")]
        System.Threading.Tasks.Task<System.Data.DataSet> GetTeachersAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserService/GetStudent", ReplyAction="http://tempuri.org/IUserService/GetStudentResponse")]
        System.Data.DataSet GetStudent(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserService/GetStudent", ReplyAction="http://tempuri.org/IUserService/GetStudentResponse")]
        System.Threading.Tasks.Task<System.Data.DataSet> GetStudentAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserService/SearchStudent", ReplyAction="http://tempuri.org/IUserService/SearchStudentResponse")]
        System.Data.DataSet SearchStudent(string input);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserService/SearchStudent", ReplyAction="http://tempuri.org/IUserService/SearchStudentResponse")]
        System.Threading.Tasks.Task<System.Data.DataSet> SearchStudentAsync(string input);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserService/Search", ReplyAction="http://tempuri.org/IUserService/SearchResponse")]
        System.Data.DataSet Search(string input);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserService/Search", ReplyAction="http://tempuri.org/IUserService/SearchResponse")]
        System.Threading.Tasks.Task<System.Data.DataSet> SearchAsync(string input);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserService/GetStudnets", ReplyAction="http://tempuri.org/IUserService/GetStudnetsResponse")]
        System.Data.DataSet GetStudnets();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserService/GetStudnets", ReplyAction="http://tempuri.org/IUserService/GetStudnetsResponse")]
        System.Threading.Tasks.Task<System.Data.DataSet> GetStudnetsAsync();
        
        // CODEGEN: Generating message contract since the operation UpdateUser is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserService/UpdateUser", ReplyAction="http://tempuri.org/IUserService/UpdateUserResponse")]
        ClientWeb.UserService.UpdateUserResponse UpdateUser(ClientWeb.UserService.UserInfo request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserService/UpdateUser", ReplyAction="http://tempuri.org/IUserService/UpdateUserResponse")]
        System.Threading.Tasks.Task<ClientWeb.UserService.UpdateUserResponse> UpdateUserAsync(ClientWeb.UserService.UserInfo request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserService/DeleteUser", ReplyAction="http://tempuri.org/IUserService/DeleteUserResponse")]
        void DeleteUser(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserService/DeleteUser", ReplyAction="http://tempuri.org/IUserService/DeleteUserResponse")]
        System.Threading.Tasks.Task DeleteUserAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserService/GetUser", ReplyAction="http://tempuri.org/IUserService/GetUserResponse")]
        System.Data.DataSet GetUser(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserService/GetUser", ReplyAction="http://tempuri.org/IUserService/GetUserResponse")]
        System.Threading.Tasks.Task<System.Data.DataSet> GetUserAsync(int id);
        
        // CODEGEN: Generating message contract since the operation SaveUser is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserService/SaveUser", ReplyAction="http://tempuri.org/IUserService/SaveUserResponse")]
        ClientWeb.UserService.SaveUserResponse SaveUser(ClientWeb.UserService.UserInfo request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserService/SaveUser", ReplyAction="http://tempuri.org/IUserService/SaveUserResponse")]
        System.Threading.Tasks.Task<ClientWeb.UserService.SaveUserResponse> SaveUserAsync(ClientWeb.UserService.UserInfo request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserService/GetAllUsers", ReplyAction="http://tempuri.org/IUserService/GetAllUsersResponse")]
        System.Data.DataSet GetAllUsers();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserService/GetAllUsers", ReplyAction="http://tempuri.org/IUserService/GetAllUsersResponse")]
        System.Threading.Tasks.Task<System.Data.DataSet> GetAllUsersAsync();
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="UserInfoObject", WrapperNamespace="http://MySchool.com/User", IsWrapped=true)]
    public partial class UserInfo {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://MySchool.com/User", Order=0)]
        public int ID;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://MySchool.com/User", Order=1)]
        public string Name;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://MySchool.com/User", Order=2)]
        public string Gender;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://MySchool.com/User", Order=3)]
        public System.DateTime DOB;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://MySchool.com/User", Order=4)]
        public ClientWeb.UserService.UserType Type;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://MySchool.com/User", Order=5)]
        public string Sub;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://MySchool.com/User", Order=6)]
        public int Std;
        
        public UserInfo() {
        }
        
        public UserInfo(int ID, string Name, string Gender, System.DateTime DOB, ClientWeb.UserService.UserType Type, string Sub, int Std) {
            this.ID = ID;
            this.Name = Name;
            this.Gender = Gender;
            this.DOB = DOB;
            this.Type = Type;
            this.Sub = Sub;
            this.Std = Std;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UpdateUserResponse {
        
        public UpdateUserResponse() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SaveUserResponse {
        
        public SaveUserResponse() {
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IUserServiceChannel : ClientWeb.UserService.IUserService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class UserServiceClient : System.ServiceModel.ClientBase<ClientWeb.UserService.IUserService>, ClientWeb.UserService.IUserService {
        
        public UserServiceClient() {
        }
        
        public UserServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public UserServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public UserServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public UserServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Data.DataSet SearchTeacher(string input) {
            return base.Channel.SearchTeacher(input);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> SearchTeacherAsync(string input) {
            return base.Channel.SearchTeacherAsync(input);
        }
        
        public System.Data.DataSet GetTeacher(int id) {
            return base.Channel.GetTeacher(id);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> GetTeacherAsync(int id) {
            return base.Channel.GetTeacherAsync(id);
        }
        
        public System.Data.DataSet GetTeachers() {
            return base.Channel.GetTeachers();
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> GetTeachersAsync() {
            return base.Channel.GetTeachersAsync();
        }
        
        public System.Data.DataSet GetStudent(int id) {
            return base.Channel.GetStudent(id);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> GetStudentAsync(int id) {
            return base.Channel.GetStudentAsync(id);
        }
        
        public System.Data.DataSet SearchStudent(string input) {
            return base.Channel.SearchStudent(input);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> SearchStudentAsync(string input) {
            return base.Channel.SearchStudentAsync(input);
        }
        
        public System.Data.DataSet Search(string input) {
            return base.Channel.Search(input);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> SearchAsync(string input) {
            return base.Channel.SearchAsync(input);
        }
        
        public System.Data.DataSet GetStudnets() {
            return base.Channel.GetStudnets();
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> GetStudnetsAsync() {
            return base.Channel.GetStudnetsAsync();
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ClientWeb.UserService.UpdateUserResponse ClientWeb.UserService.IUserService.UpdateUser(ClientWeb.UserService.UserInfo request) {
            return base.Channel.UpdateUser(request);
        }
        
        public void UpdateUser(int ID, string Name, string Gender, System.DateTime DOB, ClientWeb.UserService.UserType Type, string Sub, int Std) {
            ClientWeb.UserService.UserInfo inValue = new ClientWeb.UserService.UserInfo();
            inValue.ID = ID;
            inValue.Name = Name;
            inValue.Gender = Gender;
            inValue.DOB = DOB;
            inValue.Type = Type;
            inValue.Sub = Sub;
            inValue.Std = Std;
            ClientWeb.UserService.UpdateUserResponse retVal = ((ClientWeb.UserService.IUserService)(this)).UpdateUser(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ClientWeb.UserService.UpdateUserResponse> ClientWeb.UserService.IUserService.UpdateUserAsync(ClientWeb.UserService.UserInfo request) {
            return base.Channel.UpdateUserAsync(request);
        }
        
        public System.Threading.Tasks.Task<ClientWeb.UserService.UpdateUserResponse> UpdateUserAsync(int ID, string Name, string Gender, System.DateTime DOB, ClientWeb.UserService.UserType Type, string Sub, int Std) {
            ClientWeb.UserService.UserInfo inValue = new ClientWeb.UserService.UserInfo();
            inValue.ID = ID;
            inValue.Name = Name;
            inValue.Gender = Gender;
            inValue.DOB = DOB;
            inValue.Type = Type;
            inValue.Sub = Sub;
            inValue.Std = Std;
            return ((ClientWeb.UserService.IUserService)(this)).UpdateUserAsync(inValue);
        }
        
        public void DeleteUser(int id) {
            base.Channel.DeleteUser(id);
        }
        
        public System.Threading.Tasks.Task DeleteUserAsync(int id) {
            return base.Channel.DeleteUserAsync(id);
        }
        
        public System.Data.DataSet GetUser(int id) {
            return base.Channel.GetUser(id);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> GetUserAsync(int id) {
            return base.Channel.GetUserAsync(id);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ClientWeb.UserService.SaveUserResponse ClientWeb.UserService.IUserService.SaveUser(ClientWeb.UserService.UserInfo request) {
            return base.Channel.SaveUser(request);
        }
        
        public void SaveUser(int ID, string Name, string Gender, System.DateTime DOB, ClientWeb.UserService.UserType Type, string Sub, int Std) {
            ClientWeb.UserService.UserInfo inValue = new ClientWeb.UserService.UserInfo();
            inValue.ID = ID;
            inValue.Name = Name;
            inValue.Gender = Gender;
            inValue.DOB = DOB;
            inValue.Type = Type;
            inValue.Sub = Sub;
            inValue.Std = Std;
            ClientWeb.UserService.SaveUserResponse retVal = ((ClientWeb.UserService.IUserService)(this)).SaveUser(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ClientWeb.UserService.SaveUserResponse> ClientWeb.UserService.IUserService.SaveUserAsync(ClientWeb.UserService.UserInfo request) {
            return base.Channel.SaveUserAsync(request);
        }
        
        public System.Threading.Tasks.Task<ClientWeb.UserService.SaveUserResponse> SaveUserAsync(int ID, string Name, string Gender, System.DateTime DOB, ClientWeb.UserService.UserType Type, string Sub, int Std) {
            ClientWeb.UserService.UserInfo inValue = new ClientWeb.UserService.UserInfo();
            inValue.ID = ID;
            inValue.Name = Name;
            inValue.Gender = Gender;
            inValue.DOB = DOB;
            inValue.Type = Type;
            inValue.Sub = Sub;
            inValue.Std = Std;
            return ((ClientWeb.UserService.IUserService)(this)).SaveUserAsync(inValue);
        }
        
        public System.Data.DataSet GetAllUsers() {
            return base.Channel.GetAllUsers();
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> GetAllUsersAsync() {
            return base.Channel.GetAllUsersAsync();
        }
    }
}
